import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { ViewTransitions } from "next-view-transitions";
import Image from "next/image";
import wtspLogo from "../../public/assets/logos/whatsapp.svg";
import MobileMenu from "../../public/assets/logos/home.svg";
import Link from "next/link";
import LenisProvider from "./LenisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ILEAF",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ViewTransitions>
          <LenisProvider>
          <Navbar />
          {children}
          <Image
            src={wtspLogo}
            alt=""
            className="fixed bottom-6 right-6 size-8"
          />
          <div className="flex lg:hidden fixed bottom-6 left-6 w-full">
            <Link href="/">
          <Image src={MobileMenu} alt="" className="size-8" />
            </Link>
          </div>
          <Footer />
          </LenisProvider>
        </ViewTransitions>
      </body>
    </html>
  );
}
