export const windowsData = {
    "Windows": {
      "description": "Made of high quality Galvanised Steel with several unique features. Available in customer choice of sizes. Ready available steel thickness EPOXY Primer Coated. Attractive designs. Termite proof, Anti Corrosive. No climatic deformation as in wood. No additional cost for frame. Easy to install.",
      "series": [
        {
          "variants": [
            {
              "id": "CP CD",
              "number": "1",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters. This unique product range has several key features. Easy to install and give freedom from carpentry and wood working.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663550/CP-CD-768x700_mjjlwk.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "CP C Arch CD",
              "number": "2",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663545/cp-c-arch-cd_xacfss.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "EP Corner Window",
              "number": "3",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663552/EP-Corner-Window-768x583_rzw8ga.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "EP Luver Horizontal Check Design",
              "number": "4",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663552/EP-Luver-Horizontal-Check-Design-768x452_vz4amh.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "B Arch CD 1 Panel 1",
              "number": "5",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663548/B-Arch-CD-1-Panel_oqt5zn.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "B Arch CD 2 Panel 3",
              "number": "6",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663552/B-Arch-CD-2-Panel-3_gys8vw.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "B Arch CD 2 Panel 4",
              "number": "7",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663551/B-Arch-CD-2-Panel-4_vyphjr.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "B Arch CD 1 Panel 2",
              "number": "8",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663546/B-Arch-CD-1-Panel-B_bus6yo.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "3 Panel French (Check)",
              "number": "9",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663544/3-Panel-Check_cwjxmw.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "3 Panel Check",
              "number": "10",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663544/3-Panel-Check_cwjxmw.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "2 Panel Check",
              "number": "11",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663547/2-Panel-Check_wwmd1y.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "1 Panel Check (French)",
              "number": "12",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663553/1-Panel-Check-French_dkjkkm.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "1 Panel",
              "number": "13",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663545/1-Panel_ewdd1o.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "3 Panel",
              "number": "14",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663548/3-Panel_dkjicx.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "2 Panel",
              "number": "15",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663549/2-Panel-687x1024_jxlzfl.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "Ventilator",
              "number": "16",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663549/ventilator_yvub4v.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "C Arch H 2 Panel 1",
              "number": "17",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663547/C-Arch-H-2-Panel-1_i9rnfy.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "Exhaust Ventilator",
              "number": "18",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663546/exhaust-ventilator_reqd6y.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
            {
              "id": "C Arch H 2 Panel 2",
              "number": "19",
              "description" : "I-Leaf Steel Windows are made of high quality GI with anticorrosive treatment. They are highly economical and save time as available in ready to use steel windows with frames and shutters.",
              "image": "https://res.cloudinary.com/db4zbyipc/image/upload/v1751663551/C-Arch-H-2-Panel-2_rkqerq.webp",
              "cta": "VIEW DETAILS",
              "details": {
                "material": "Made of high quality Galvanised Steel with several unique features.",
                "sizes": "Available in customer choice of sizes",
                "thickness": "Ready available steel thickness",
                "coating": "EPOXY Primer Coated.",
                "designs": "Attractive designs",
                "features": "Termite proof, Anti Corrosive.",
                "frameIncluded": "No climatic deformation as in wood.",
                "cost": "No additional cost for frame.",
                "installation": "Easy to install",
              }
            },
          ]
        }
      ]
    }
  };